spring:
  application:
    name: bus-ticketing-user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bus_ticketing}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bus-ticketing}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/bus-ticketing/protocol/openid-connect/certs}

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8081}/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}

app:
  config:
    keycloak:
      server-url: http://localhost:8080
      realm: bus-ticketing
      clientId: bus-ticketing-client
      client-secret: chms6p6XoccAEzzsOVpob3Rsnsr1Dzv6

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.bus.ticketing: DEBUG
    org.hibernate: INFO

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://172.25.0.12:9411/api/v2/spans

# spring:
#   datasource:
#     url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:bus_ticketing}
#   eureka:
#     client:
#       service-url:
#         defaultZone: http://${EUREKA_HOST:bus-ticketing-service-registry}:${EUREKA_PORT:8081}/eureka
#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak_web:8080/realms/bus-ticketing}
#           jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak_web:8080/realms/bus-ticketing/protocol/openid-connect/certs}

# logging:
#   level:
#     root: INFO
#     org.springframework: INFO
#     com.bus.ticketing: INFO
#     org.hibernate: WARN 