spring:
  config:
    activate:
      on-profile: docker

  cloud:
    config:
      server:
        git:
          uri: file:///config-repo
          default-label: docker
          search-paths: '{application}'
          clone-on-start: true
          force-pull: true

eureka:
  client:
    service-url:
      defaultZone: http://bus-ticketing-service-registry:8081/eureka/
  instance:
    prefer-ip-address: true
    hostname: bus-ticketing-config-server 