spring:
  application:
    name: bus-ticketing-core-service
  datasource:
    url: postgresql://postgres:gWdPhKsfjxwNiiOxkFwPhTfWbtUKlMhB@switchback.proxy.rlwy.net:37854/railway
    username: postgres
    password: gWdPhKsfjxwNiiOxkFwPhTfWbtUKlMhB
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

info:
  app:
    name: ${spring.application.name}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://172.25.0.12:9411/api/v2/spans    


# server:
#   port: 8092

# spring:
#   datasource:
#     url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bus_ticketing_dev}
#   jpa:
#     hibernate:
#       ddl-auto: create-drop
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bus-ticketing-dev}
#           jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/bus-ticketing-dev/protocol/openid-connect/certs}

# # Core Service Test Data
# core:
#   service:
#     test-data:
#       enabled: true
#       location: classpath:test-data/

# logging:
#   level:
#     root: DEBUG
#     org.springframework: DEBUG
#     com.bus.ticketing: DEBUG
#     org.hibernate: DEBUG
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type.descriptor.sql: DEBUG 