spring:
  application:
    name: bus-ticketing-core-service
  datasource:
    url: postgresql://postgres:gWdPhKsfjxwNiiOxkFwPhTfWbtUKlMhB@switchback.proxy.rlwy.net:37854/railway
    username: postgres
    password: gWdPhKsfjxwNiiOxkFwPhTfWbtUKlMhB
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

info:
  app:
    name: bus-ticketing-core-service

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://172.25.0.12:9411/api/v2/spans    

# spring:
#   datasource:
#     url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:bus_ticketing}
#   eureka:
#     client:
#       service-url:
#         defaultZone: http://${EUREKA_HOST:bus-ticketing-service-registry}:${EUREKA_PORT:8081}/eureka
#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak_web:8080/realms/bus-ticketing}
#           jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak_web:8080/realms/bus-ticketing/protocol/openid-connect/certs}

# # Core Service Production Settings
# core:
#   service:
#     test-data:
#       enabled: false

# logging:
#   level:
#     root: INFO
#     org.springframework: INFO
#     com.bus.ticketing: INFO
#     org.hibernate: WARN 