spring:
  config:
    activate:
      on-profile: dev

  cloud:
    config:
      server:
        git:
          uri: file:///config-repo
          default-label: dev
          search-paths: '{application}'
          clone-on-start: true
          force-pull: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always 